version: 2
updates:

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*:*"
        update-types: ["version-update:semver-patch"]
    reviewers:
      - "Dauren-Delmukhambetov"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Dauren-Delmukhambetov"
