AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Stage:
    Type: String
    Default: dev
Resources:
  DataMaskerApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: !Ref Stage
      Models:
        DataMaskingRequest:
          type: object
          required:
            - data
          properties:
            data:
              type: string
  DataMaskerLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      AutoPublishAlias: !Ref Stage
      Runtime: java11
      Handler: org.serverless.umbrella.Handler::handleRequest
      MemorySize: 1024
      Timeout: 300
      CodeUri: build/distributions/data-masker-0.1.0.zip
      Events:
        DataMaskerApiEvent:
          Type: Api
          Properties:
            Path: /data-masker
            Method: post
            RequestModel:
              Model: DataMaskingRequest
              Required: true
            RestApiId:
              Ref: DataMaskerApi
